language: rust
branches:
  only:
    - master
matrix:
  include:
    - os: linux
      rust: stable
    - os: linux
      rust: beta
    - os: linux
      rust: nightly
    - os: osx
      rust: stable
    - os: windows
      rust: stable
  allow_failures:
    - rust: nightly
script:
  - cargo check --all --tests
  - cargo build --all
  - cargo test --all --exclude uint --exclude fixed-hash
  - cd fixed-hash/ && cargo test --all-features && cd ..
  - cd uint/ && cargo test --features=std,quickcheck --release && cd ..
  - cd hashdb/ && cargo test --no-default-features && cd ..
  - cd plain_hasher/ && cargo test --no-default-features && cd ..
